USE [master]
GO
CREATE LOGIN [usr_dq] WITH PASSWORD=N'prjDQ2023!', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [DQ]
GO
CREATE USER [usr_dq] FOR LOGIN [usr_dq]
GO
USE [DQ]
GO
ALTER ROLE [db_owner] ADD MEMBER [usr_dq]
GO
