CREATE VIEW dbo.VW_VENDAS
AS
SELECT 

V.CODIGO_VENDA
,CONVERT(VARCHAR(10),V.DATA_VENDA,103) DATA_VENDA
,C.NOME_CLIENTE
,P.DESCRICAO_PRODUTO
,CP.DECRICAO_CATEGORIA
,VD.NOME_VENDEDOR
,L.NOME_LOJA
,L.LOCALIDADE_LOJA
,L.TIPO_LOJA
,IV.VALOR_UNITARIO
,IV.QUANTIDADE
,IV.VALOR_FINAL
,FP.DESCRICAO_FORMA_PAGAMENTO

FROM			dbo.TB_VENDA v 

INNER JOIN		dbo.TB_ITEM_VENDA IV
ON				V.CODIGO_VENDA = IV.CODIGO_VENDA

INNER JOIN		dbo.TB_CLIENTE C
ON				V.CODIGO_CLIENTE = C.CODIGO_CLIENTE 

INNER JOIN		dbo.TB_PRODUTO P 
ON				IV.CODIGO_PRODUTO = P.CODIGO_PRODUTO

INNER JOIN		dbo.TB_CATEGORIA_PRODUTO CP
ON				P.CODIGO_CATEGORIA = CP.CODIGO_CATEGORIA

INNER JOIN		dbo.TB_VENDEDOR VD
ON				V.CODIGO_VENDEDOR = VD.CODIGO_VENDEDOR

INNER JOIN		dbo.TB_LOJA L
ON				V.CODIGO_LOJA = L.CODIGO_LOJA 

INNER JOIN		dbo.TB_FORMA_PAGAMENTO FP
ON				V.FORMA_PAGAMENTO = FP.CODIGO_FORMA_PAGAMENTO
GO

SELECT DESCRICAO_PRODUTO , SUM(VALOR_FINAL) VALOR_FINAL
FROM dbo.VW_VENDAS
GROUP BY DESCRICAO_PRODUTO 
ORDER BY VALOR_FINAL DESC
GO

SELECT NOME_VENDEDOR , SUM(VALOR_FINAL) VALOR_FINAL
FROM dbo.VW_VENDAS
GROUP BY NOME_VENDEDOR 
ORDER BY VALOR_FINAL DESC
GO

SELECT NOME_LOJA , SUM(VALOR_FINAL) VALOR_FINAL
FROM dbo.VW_VENDAS
GROUP BY NOME_LOJA
ORDER BY VALOR_FINAL DESC
GO