site_name: Projeto BI com Azure
theme:
  name: material
  features:
    - content.code.copy
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Modo Claro
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Modo Escuro
  
nav:
  - Home do Projeto: index.md
  - Quem sou eu?: 0_quem_sou_eu.md
  - 1. O que iremos abordar?: 1_projeto.md
  - 2. Recursos que iremos usar do Azure: 2_provisionando_recursos_azure.md
  - 3. Modelagem Dimensional: 3_modelagem_dados.md  
  - 4. Desmistificando ETL/ELT: 4_etl_elt.md
  - 5. Imersão em Arquitetura de Dados: 5_arquitetura_dados.md  
  - 6. Entendendo a Arquitetura Medalhão: 6_arquitetura_medalhao.md
  - 7. Conhecendo DW - Data Lake - LakeHouse: 7_dw_data_lake_lakehouse.md
  - 8. Segurança: 8_seguranca.md
  - 9. CI/CD - Git - GitHub - Azure DevOps: 9_cicd.md
  - 10. Data Quality - Apresentação de um Framework: 10_data_quality.md
  - 11. Monitoramento e Parametrização de uma Pipeline no Azure Data Factory: 11_monitoramento_parametrizacao_pipeline.md  
  - 12. Gerando a Massa de Dados: 12_gerar_massa_dados.md      
  - 13. Carga de Dados no SQL Server Camada Relacional: 13_carga_sql_server_relacional.md    
  - 14. Carga de Dados no SQL Server Camada Multidimensional: 14_carga_sql_server_multidimensional.md    
  - 15. Onde encontro os arquivos?: 15_arquivos.md      
  - 16. Formulário de Inscrição: 16_formulario.md        

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true